"""empty message

Revision ID: 01add9e1d179
Revises: 
Create Date: 2022-05-05 15:47:09.870237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01add9e1d179'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_try', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_try')
    # ### end Alembic commands ###
